// Build the runtime artifact: regenerate the opcode table from the Rust
// source of truth, then bundle src/index.ts into one minified IIFE.
// - Identifier mangling only. Property names are NEVER mangled: `__hk`, `__t`,
//   and the DOM API surface are load-bearing. (Opcodes are individual exported
//   consts precisely so they mangle/inline; an object's keys would not.)
// - `BASE` stays a free (external) global — the capsule injects it.
// - dist/runtime.js (readable) is emitted beside dist/runtime.min.js for
//   debugging; only the .min.js is embedded by the rwire crate (via sync.mjs).
import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { gzipSync } from "node:zlib";

// --- step 0: regenerate src/opcodes.ts from protocol/opcodes.rs (RT3) ---
const RUST_OPCODES = new URL(
  "../libs/rwire/src/protocol/opcodes.rs",
  import.meta.url,
);
const rust = readFileSync(RUST_OPCODES, "utf8");
const consts = [...rust.matchAll(/pub const ([A-Z_0-9]+): u8 = (0x[0-9A-Fa-f]+);/g)];
if (consts.length < 40) throw new Error(`opcode parse suspiciously short: ${consts.length}`);
// Event-type byte values from the Ev enum (EV_CLICK, EV_VISIBLE, …).
const evBlock = rust.slice(rust.indexOf("pub enum Ev"));
const evs = [...evBlock.slice(0, evBlock.indexOf("}")).matchAll(
  /([A-Za-z0-9]+) = (0x[0-9A-Fa-f]+) => "/g,
)];
if (evs.length < 10) throw new Error(`event parse suspiciously short: ${evs.length}`);
const generated =
  "// GENERATED by build.mjs from libs/rwire/src/protocol/opcodes.rs — DO NOT EDIT.\n" +
  "// Wire opcode + event-type byte values; unused exports are tree-shaken.\n" +
  consts.map(([, name, hex]) => `export const ${name} = ${hex.toLowerCase()};`).join("\n") +
  "\n" +
  evs.map(([, name, hex]) => `export const EV_${name.toUpperCase()} = ${hex.toLowerCase()};`).join("\n") +
  "\n";
const opcodesPath = new URL("src/opcodes.ts", import.meta.url);
let current = "";
try {
  current = readFileSync(opcodesPath, "utf8");
} catch {}
if (current !== generated) writeFileSync(opcodesPath, generated);

// --- bundle ---
const shared = {
  entryPoints: ["src/index.ts"],
  bundle: true,
  format: "iife",
  target: "es2020",
  charset: "utf8",
  legalComments: "none",
};

await build({ ...shared, outfile: "dist/runtime.js", minify: false });
await build({ ...shared, outfile: "dist/runtime.min.js", minify: true });

// Strip the trailing newline esbuild appends so the embedded artifact is a
// single clean line, then report sizes (the capsule-size budget tracks these).
const min = readFileSync("dist/runtime.min.js", "utf8").trimEnd();
writeFileSync("dist/runtime.min.js", min);
const gz = gzipSync(Buffer.from(min)).length;
console.log(`runtime.min.js: ${min.length} bytes (${gz} gzipped)`);

// --- extensions: separately-built lazy modules (ESM for dynamic import) ---
mkdirSync(new URL("dist/ext/", import.meta.url), { recursive: true });
await build({
  entryPoints: [new URL("src/ext/vim.ts", import.meta.url).pathname],
  bundle: true,
  format: "esm",
  minify: true,
  outfile: new URL("dist/ext/vim.min.js", import.meta.url).pathname,
});
{
  const out = readFileSync(new URL("dist/ext/vim.min.js", import.meta.url));
  console.log(`ext/vim.min.js: ${out.length} bytes (${gzipSync(out).length} gzipped)`);
}
