//! State management for rwire.
//!
//! This module provides traits and types for managing state with different
//! storage strategies:
//!
//! - **MemoryState**: Server memory state (per-connection, default)
//! - **PersistedState**: Database-backed state (survives disconnects)
//!
//! Use `#[derive(State)]` with `#[storage(...)]` attribute to specify storage:
//!
//! ```ignore
//! use rwire::State;
//!
//! #[derive(State, Default)]
//! #[storage(memory)]  // or omit for default
//! struct SessionState { user_id: Option<u64> }
//!
//! #[derive(State)]
//! #[storage(persisted, table = "notes")]
//! struct Note { id: u64, content: String }
//! ```

use std::any::{Any, TypeId};
use std::cell::Cell;
use std::collections::HashMap;
use std::sync::OnceLock;

// ============================================================================
// Fine-Grained Reactivity Types
// ============================================================================

/// Renderer dependency tracking using compile-time bitmasks.
///
/// Field IDs (0-63) map to bit positions in a u64. This enables zero-cost
/// dependency checking at runtime using a single bitwise AND operation.
///
/// # Example
///
/// ```ignore
/// // Auto-generated by #[renderer] macro:
/// const DEPS: RendererDeps = RendererDeps::from_fields(&[Counter::FIELD_COUNT]);
/// ```
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct RendererDeps {
    /// Bitmask where bit i is set if renderer depends on field i
    pub mask: u64,
    /// If true, ignore mask and always re-render (fallback for complex cases)
    pub always: bool,
}

impl RendererDeps {
    /// Create deps that always re-render (fallback for dynamic dependencies).
    ///
    /// Use this for renderers that have complex or dynamic field access patterns
    /// that can't be statically analyzed.
    pub const fn always() -> Self {
        Self {
            mask: 0,
            always: true,
        }
    }

    /// Create deps from compile-time field IDs.
    ///
    /// Field IDs are generated by `#[derive(State)]` as `Type::FIELD_*` constants.
    /// Only fields 0-63 are supported; higher IDs are ignored.
    pub const fn from_fields(field_ids: &[u8]) -> Self {
        let mut mask = 0u64;
        let mut i = 0;
        while i < field_ids.len() {
            if field_ids[i] < 64 {
                mask |= 1u64 << field_ids[i];
            }
            i += 1;
        }
        Self {
            mask,
            always: false,
        }
    }

    /// Create deps with no dependencies (never re-renders automatically).
    pub const fn none() -> Self {
        Self {
            mask: 0,
            always: false,
        }
    }

    /// Check if this renderer needs update given changed fields.
    ///
    /// Returns true if:
    /// - `always` is set, OR
    /// - `changes.all_changed` is set, OR
    /// - There's overlap between dependency mask and change mask
    #[inline]
    pub const fn needs_update(&self, changes: ChangeSet) -> bool {
        self.always || changes.all_changed || (self.mask & changes.mask) != 0
    }

    /// Merge two RendererDeps (union of dependencies).
    pub const fn merge(self, other: Self) -> Self {
        Self {
            mask: self.mask | other.mask,
            always: self.always || other.always,
        }
    }
}

/// Tracks which fields changed during a handler execution.
///
/// Uses the same u64 bitmask as RendererDeps for zero-cost comparison.
/// This is generated by the `#[handler]` macro based on static analysis
/// of field mutations in the handler body.
///
/// # Example
///
/// ```ignore
/// // Auto-generated by #[handler] macro:
/// const CHANGES: ChangeSet = ChangeSet::from_fields(&[Counter::FIELD_COUNT]);
/// ```
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ChangeSet {
    /// Bitmask where bit i is set if field i was modified
    pub mask: u64,
    /// If true, assume all fields changed (fallback for complex mutations)
    pub all_changed: bool,
}

impl ChangeSet {
    /// Create an empty changeset (no fields changed).
    pub const fn new() -> Self {
        Self {
            mask: 0,
            all_changed: false,
        }
    }

    /// Create a changeset indicating all fields changed.
    ///
    /// Use this as a fallback when mutations can't be statically determined,
    /// or for handlers that use methods like `push()`, `retain()`, etc.
    pub const fn all() -> Self {
        Self {
            mask: !0,
            all_changed: true,
        }
    }

    /// Create changeset from compile-time field IDs.
    ///
    /// Field IDs are generated by `#[derive(State)]` as `Type::FIELD_*` constants.
    pub const fn from_fields(field_ids: &[u8]) -> Self {
        let mut mask = 0u64;
        let mut i = 0;
        while i < field_ids.len() {
            if field_ids[i] < 64 {
                mask |= 1u64 << field_ids[i];
            }
            i += 1;
        }
        Self {
            mask,
            all_changed: false,
        }
    }

    /// Check if any field changed.
    pub const fn is_empty(&self) -> bool {
        !self.all_changed && self.mask == 0
    }

    /// Merge two changesets (union of changes).
    pub const fn merge(self, other: Self) -> Self {
        Self {
            mask: self.mask | other.mask,
            all_changed: self.all_changed || other.all_changed,
        }
    }

    /// Add a single field to the changeset.
    pub const fn with_field(mut self, field_id: u8) -> Self {
        if field_id < 64 {
            self.mask |= 1u64 << field_id;
        }
        self
    }
}

use crate::builder::ElementBuilder;
use crate::item_ref::ItemRef;

// ============================================================================
// EventContext - Payload data passed to handlers
// ============================================================================

/// Payload data from a client event.
///
/// Different event types provide different payload types:
/// - `input`/`change` on `<input>`/`<textarea>` → `Text(value)`
/// - `click` on element with `data-*` attrs → `Data(attrs)`
/// - `submit` on `<form>` → `Form(field_values)`
#[derive(Debug, Clone)]
pub enum EventPayload {
    /// Text value from input.value or textarea.value
    Text(String),
    /// Data attributes from the clicked element (data-id="5" → {"id": "5"})
    Data(HashMap<String, String>),
    /// Form field values from form submission
    Form(HashMap<String, String>),
    /// No payload data
    Empty,
}

/// Context passed to handlers with 2-parameter signatures.
///
/// Provides access to event payload data such as input values, data attributes,
/// and form field values. The payload is parsed lazily on first access.
///
/// Also provides access to handler parameter bytes for ItemRef-based handlers.
///
/// # Example
///
/// ```ignore
/// #[handler]
/// fn add_todo(state: &mut TodoState, ctx: &EventContext) {
///     if let Some(text) = ctx.text() {
///         state.items.push(Todo::new(text.to_string()));
///     }
/// }
///
/// #[handler]
/// fn delete_item(state: &mut TodoState, ctx: &EventContext) {
///     if let Some(id) = ctx.data("id").and_then(|s| s.parse().ok()) {
///         state.items.retain(|item| item.id != id);
///     }
/// }
///
/// // ItemRef-based handler (cleaner API)
/// #[handler]
/// fn toggle_item(state: &mut TodoState, ctx: &EventContext) {
///     if let Some(item_ref) = ctx.item_ref::<TodoItem>() {
///         if let Some(item) = item_ref.get_mut(&mut state.items) {
///             item.done = !item.done;
///         }
///     }
/// }
/// ```
pub struct EventContext {
    /// Raw payload bytes from the client (JSON for form/text events)
    raw: Vec<u8>,
    /// Lazily parsed payload
    parsed: OnceLock<EventPayload>,
    /// Handler parameter bytes (for ItemRef-based handlers)
    param_bytes: Vec<u8>,
    /// A client navigation the handler requested via `navigate`/`replace_route`,
    /// flushed to this connection after the handler's synced update.
    navigation: Cell<Option<Navigation>>,
}

/// A server-initiated client navigation requested from a handler.
pub(crate) struct Navigation {
    pub url: String,
    pub replace: bool,
}

impl EventContext {
    /// Create a new EventContext from raw payload bytes.
    pub fn new(raw: Vec<u8>) -> Self {
        Self {
            raw,
            parsed: OnceLock::new(),
            param_bytes: Vec::new(),
            navigation: Cell::new(None),
        }
    }

    /// Create a new EventContext with both payload and param bytes.
    pub fn new_with_params(raw: Vec<u8>, param_bytes: Vec<u8>) -> Self {
        Self {
            raw,
            parsed: OnceLock::new(),
            param_bytes,
            navigation: Cell::new(None),
        }
    }

    /// Create an empty EventContext (no payload).
    pub fn empty() -> Self {
        Self {
            raw: Vec::new(),
            parsed: OnceLock::new(),
            param_bytes: Vec::new(),
            navigation: Cell::new(None),
        }
    }

    /// Request a client navigation: push `url` onto history (back returns here).
    /// Use this when a handler creates or selects a resource whose URL is only
    /// known server-side — the URL updates after the handler's DOM update lands.
    pub fn navigate(&self, url: impl Into<String>) {
        self.navigation.set(Some(Navigation {
            url: url.into(),
            replace: false,
        }));
    }

    /// Request a client navigation that replaces the current history entry.
    pub fn replace_route(&self, url: impl Into<String>) {
        self.navigation.set(Some(Navigation {
            url: url.into(),
            replace: true,
        }));
    }

    /// Take the navigation the handler requested, if any (server-internal).
    pub(crate) fn take_navigation(&self) -> Option<Navigation> {
        self.navigation.take()
    }

    /// Create an EventContext with a text payload (e.g., a route path).
    ///
    /// This is used internally by the server to deliver route change messages
    /// to route handlers via `ctx.text()`.
    pub fn from_text(text: &str) -> Self {
        let json = serde_json::json!({"t": "text", "v": text});
        Self::new(json.to_string().into_bytes())
    }

    /// Get the parsed payload, parsing lazily if needed.
    pub fn payload(&self) -> &EventPayload {
        self.parsed.get_or_init(|| self.parse_payload())
    }

    /// Parse the raw payload bytes into an EventPayload.
    fn parse_payload(&self) -> EventPayload {
        if self.raw.is_empty() {
            return EventPayload::Empty;
        }

        // Try to parse as JSON
        let json_str = match std::str::from_utf8(&self.raw) {
            Ok(s) => s,
            Err(_) => return EventPayload::Empty,
        };

        // Parse JSON object with type discriminator
        let parsed: serde_json::Value = match serde_json::from_str(json_str) {
            Ok(v) => v,
            Err(_) => return EventPayload::Empty,
        };

        let obj = match parsed.as_object() {
            Some(o) => o,
            None => return EventPayload::Empty,
        };

        let payload_type = obj.get("t").and_then(|v| v.as_str()).unwrap_or("");
        let value = obj.get("v");

        match payload_type {
            "text" => {
                if let Some(s) = value.and_then(|v| v.as_str()) {
                    EventPayload::Text(s.to_string())
                } else {
                    EventPayload::Empty
                }
            }
            "data" => {
                if let Some(obj) = value.and_then(|v| v.as_object()) {
                    let map: HashMap<String, String> = obj
                        .iter()
                        .filter_map(|(k, v)| v.as_str().map(|s| (k.clone(), s.to_string())))
                        .collect();
                    EventPayload::Data(map)
                } else {
                    EventPayload::Empty
                }
            }
            "form" => {
                if let Some(obj) = value.and_then(|v| v.as_object()) {
                    let map: HashMap<String, String> = obj
                        .iter()
                        .filter_map(|(k, v)| v.as_str().map(|s| (k.clone(), s.to_string())))
                        .collect();
                    EventPayload::Form(map)
                } else {
                    EventPayload::Empty
                }
            }
            _ => EventPayload::Empty,
        }
    }

    /// Get text value if this is a text payload.
    ///
    /// Returns `Some(&str)` for `input` or `change` events on input/textarea elements.
    pub fn text(&self) -> Option<&str> {
        match self.payload() {
            EventPayload::Text(s) => Some(s.as_str()),
            _ => None,
        }
    }

    /// Get a data attribute value if this is a data payload.
    ///
    /// Returns `Some(&str)` for `click` events on elements with matching data-* attribute.
    ///
    /// # Example
    ///
    /// For an element with `data-id="5"`, `ctx.data("id")` returns `Some("5")`.
    pub fn data(&self, key: &str) -> Option<&str> {
        match self.payload() {
            EventPayload::Data(map) => map.get(key).map(|s| s.as_str()),
            _ => None,
        }
    }

    /// Get a form field value if this is a form payload.
    ///
    /// Returns `Some(&str)` for `submit` events on form elements.
    pub fn field(&self, name: &str) -> Option<&str> {
        match self.payload() {
            EventPayload::Form(map) => map.get(name).map(|s| s.as_str()),
            _ => None,
        }
    }

    /// Check if the payload is empty.
    pub fn is_empty(&self) -> bool {
        matches!(self.payload(), EventPayload::Empty)
    }

    /// Get the raw payload bytes.
    pub fn raw(&self) -> &[u8] {
        &self.raw
    }

    /// Get the handler parameter bytes.
    pub fn param_bytes(&self) -> &[u8] {
        &self.param_bytes
    }

    /// Check if this context has parameter bytes (from on_ref binding).
    pub fn has_params(&self) -> bool {
        !self.param_bytes.is_empty()
    }

    /// Extract an ItemRef from the parameter bytes.
    ///
    /// This is used with handlers bound via `on_ref()`. The ItemRef was
    /// encoded when binding the event and sent back with the event.
    ///
    /// # Example
    ///
    /// ```ignore
    /// #[handler]
    /// fn toggle_item(state: &mut TodoState, ctx: &EventContext) {
    ///     if let Some(item_ref) = ctx.item_ref::<TodoItem>() {
    ///         if let Some(item) = item_ref.get_mut(&mut state.items) {
    ///             item.done = !item.done;
    ///         }
    ///     }
    /// }
    /// ```
    pub fn item_ref<T: 'static>(&self) -> Option<ItemRef<T>> {
        if self.param_bytes.is_empty() {
            return None;
        }
        ItemRef::decode(&self.param_bytes).map(|(r, _)| r)
    }

    /// Get the item index from the parameter bytes.
    ///
    /// This is a lower-level alternative to `item_ref()` that just returns
    /// the index without type information.
    pub fn item_index(&self) -> Option<usize> {
        self.item_ref::<()>().map(|r| r.index())
    }
}

impl std::fmt::Debug for EventContext {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EventContext")
            .field("payload", self.payload())
            .finish()
    }
}

// ============================================================================
// Storage Type Enum
// ============================================================================

/// Storage type for state, determined at compile time via `#[storage(...)]` attribute.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StorageType {
    /// Server memory state (per-connection, default)
    Memory,
    /// Database-backed state (survives disconnects)
    Persisted,
    /// Process-global in-memory state, shared by every connection.
    ///
    /// One instance exists for the whole server (not one per connection like
    /// `Memory`), but it is never persisted to a database like `Persisted`.
    /// Ideal for live server-wide data such as metrics polled by a background
    /// task. Mutate from a handler (`&mut T`) or, off-connection, via
    /// [`SharedServerState::update_shared`](crate::SharedServerState::update_shared).
    Shared,
}

// ============================================================================
// State Traits
// ============================================================================

/// Marker trait for memory state types (server-side, per-connection).
///
/// Memory state lives in server RAM and is the default storage type.
/// State is lost when the connection closes. Ideal for:
/// - Session data
/// - Computed views
/// - Temporary application state
///
/// # Example
///
/// ```ignore
/// #[derive(State, Default)]
/// #[storage(memory)]  // or just omit #[storage] for default
/// struct SessionState {
///     user_id: Option<u64>,
/// }
/// ```
pub trait MemoryState: Default + Send + Sync + 'static {
    /// Return the storage type (always Memory for this trait).
    fn storage_type() -> StorageType {
        StorageType::Memory
    }
}

/// Marker trait for persisted state types (database-backed).
///
/// Persisted state is stored in a database and survives disconnects.
/// Changes are automatically saved after handler execution. Ideal for:
/// - User data
/// - Preferences
/// - Documents
///
/// # Example
///
/// ```ignore
/// #[derive(State)]
/// #[storage(persisted, table = "notes")]
/// struct Note {
///     #[key]
///     id: u64,
///     content: String,
/// }
/// ```
pub trait PersistedState: Send + Sync + 'static {
    /// Return the storage type (always Persisted for this trait).
    fn storage_type() -> StorageType {
        StorageType::Persisted
    }

    /// Return the table name for this persisted state.
    fn table_name() -> &'static str;

    /// Return the key field name for this persisted state.
    fn key_field() -> &'static str;
}

// ============================================================================
// Unified State Trait
// ============================================================================

/// Unified trait for all state types, with storage type as an associated constant.
///
/// This trait is implemented by the `#[derive(State)]` macro based on the
/// `#[storage(...)]` attribute. The `STORAGE_TYPE` constant determines how
/// handlers for this state behave:
///
/// - `Memory`: Handlers execute on the server (default)
/// - `Persisted`: Handlers execute on server and persist to database
///
/// # Example
///
/// ```ignore
/// #[derive(State, Default)]
/// struct Counter { count: i32 }  // Memory is default
/// ```
pub trait State: Send + Sync + 'static {
    /// The storage type for this state, known at compile time.
    const STORAGE_TYPE: StorageType;

    /// Table name for persisted state (empty for non-persisted).
    const TABLE_NAME: &'static str = "";

    /// Key field name for persisted state (empty for non-persisted).
    const KEY_FIELD: &'static str = "";
}

// ============================================================================
// HandlerSpec - Bridge between macros and runtime
// ============================================================================

/// Specification for a handler, determining its execution strategy.
///
/// The `#[handler]` macro generates this instead of `HandlerFn`. The storage
/// type of the state determines whether the handler requires a server round-trip.
#[derive(Clone)]
pub struct HandlerSpec {
    /// The storage type of the state this handler operates on.
    pub storage_type: StorageType,
    /// The TypeId of the state this handler operates on.
    pub state_type_id: Option<TypeId>,
    /// The remote handler function.
    pub remote_handler: Option<HandlerFn>,
    /// Parameter bytes to send with the event (for ItemRef-based handlers).
    /// These bytes are encoded when binding the event and sent back with the event.
    pub param_bytes: Option<Vec<u8>>,
    /// Set of fields that this handler modifies.
    /// Used for fine-grained reactivity - only renderers depending on these
    /// fields will re-render after this handler executes.
    pub changes: ChangeSet,
    /// Debounce delay in milliseconds (0 = no debounce).
    /// When > 0, uses BIND_DEBOUNCED opcode instead of BIND_REMOTE.
    pub debounce_ms: u16,
    /// Stable, content-derived handler identity (FNV-1a of the handler's
    /// module path + name, set by the `#[handler]` macro).
    ///
    /// Sent on the wire instead of a positional table index, so a binding maps
    /// to the same id across renders, restarts, and reconnects — the basis for
    /// reusing DOM nodes (morphing) without misrouting events. `0` = unset
    /// (handlers built without the macro); such handlers fall back to a
    /// content hash at registration time.
    pub handler_id: u32,
}

impl HandlerSpec {
    /// Create a HandlerSpec from a handler function and state type.
    ///
    /// This legacy method assumes all fields change (ChangeSet::all()).
    /// For fine-grained reactivity, use `from_fn_with_changes` instead.
    pub fn from_fn<S: State + Default + 'static>(handler: fn(&mut S)) -> Self {
        Self::from_fn_with_changes::<S>(handler, ChangeSet::all())
    }

    /// Create a HandlerSpec from a handler function with explicit ChangeSet.
    ///
    /// This is called by the `#[handler]` macro with auto-detected changes.
    pub fn from_fn_with_changes<S: State + Default + 'static>(
        handler: fn(&mut S),
        changes: ChangeSet,
    ) -> Self {
        Self {
            storage_type: S::STORAGE_TYPE,
            state_type_id: Some(TypeId::of::<S>()),
            remote_handler: Some(HandlerFn::new_state_with_changes::<S>(handler, changes)),
            param_bytes: None,
            changes,
            debounce_ms: 0,
            handler_id: 0,
        }
    }

    /// Create a HandlerSpec from a handler function with EventContext.
    ///
    /// This legacy method assumes all fields change (ChangeSet::all()).
    /// For fine-grained reactivity, use `from_fn_with_context_and_changes` instead.
    pub fn from_fn_with_context<S: State + Default + 'static>(
        handler: fn(&mut S, &EventContext),
    ) -> Self {
        Self::from_fn_with_context_and_changes::<S>(handler, ChangeSet::all())
    }

    /// Create a HandlerSpec from a handler function with EventContext and explicit ChangeSet.
    ///
    /// This is called by the `#[handler]` macro for handlers with EventContext parameter.
    pub fn from_fn_with_context_and_changes<S: State + Default + 'static>(
        handler: fn(&mut S, &EventContext),
        changes: ChangeSet,
    ) -> Self {
        Self {
            storage_type: S::STORAGE_TYPE,
            state_type_id: Some(TypeId::of::<S>()),
            remote_handler: Some(HandlerFn::new_with_context_and_changes::<S>(
                handler, changes,
            )),
            param_bytes: None,
            changes,
            debounce_ms: 0,
            handler_id: 0,
        }
    }

    /// Create a memory HandlerSpec with a remote handler.
    pub fn memory<S: MemoryState>(handler: fn(&mut S)) -> Self {
        Self {
            storage_type: StorageType::Memory,
            state_type_id: Some(TypeId::of::<S>()),
            remote_handler: Some(HandlerFn::new::<S>(handler)),
            param_bytes: None,
            changes: ChangeSet::all(),
            debounce_ms: 0,
            handler_id: 0,
        }
    }

    /// Get the ChangeSet for this handler.
    pub fn changes(&self) -> ChangeSet {
        self.changes
    }

    /// Add parameter bytes to this handler spec (returns a new spec).
    ///
    /// This is used by `ElementBuilder::on_ref()` to attach item reference
    /// data to the handler.
    pub fn with_param_bytes(mut self, bytes: Vec<u8>) -> Self {
        self.param_bytes = Some(bytes);
        self
    }

    /// Set debounce delay in milliseconds.
    ///
    /// The handler will only fire after `ms` milliseconds of inactivity.
    /// This is equivalent to using `on_debounced()` but as a builder method.
    ///
    /// # Example
    ///
    /// ```ignore
    /// el(El::Input).on(Ev::Input, search_handler().debounce(300))
    /// ```
    pub fn debounce(mut self, ms: u16) -> Self {
        self.debounce_ms = ms;
        self
    }

    /// Set the stable handler id (called by the `#[handler]` macro).
    pub fn with_handler_id(mut self, id: u32) -> Self {
        self.handler_id = id;
        self
    }

    /// The stable handler id, or `0` if it was not assigned by the macro.
    pub fn handler_id(&self) -> u32 {
        self.handler_id
    }

    /// Get the state type ID.
    pub fn state_type_id(&self) -> Option<TypeId> {
        self.state_type_id
    }

    /// Get the remote handler, if any.
    pub fn remote_handler(&self) -> Option<&HandlerFn> {
        self.remote_handler.as_ref()
    }
}

/// Largest value the 3-byte wire varint can carry (see `protocol::varint`).
///
/// Handler ids travel as varints in bind/event frames, so they must fit this
/// range — a wider value would be silently truncated on the wire and never
/// resolve back to its map entry.
pub const HANDLER_ID_MAX: u32 = 0x0040_0000 - 1; // 22-bit space, < VARINT_MAX

/// Compute a stable handler id from a handler's module path and name.
///
/// FNV-1a (32-bit) over `"<module>::<name>"`, folded into the wire-varint range
/// ([`HANDLER_ID_MAX`]). Deterministic across renders, process restarts, and
/// reconnects, so a binding resolves to the same id over time. Used by the
/// `#[handler]` macro via `module_path!()` + the fn name. Never returns `0`
/// (which is reserved for "unset").
#[must_use]
pub fn stable_handler_id(module: &str, name: &str) -> u32 {
    let mut h: u32 = 0x811c_9dc5;
    let mix = |h: &mut u32, b: u8| {
        *h ^= u32::from(b);
        *h = h.wrapping_mul(0x0100_0193);
    };
    for b in module.bytes() {
        mix(&mut h, b);
    }
    mix(&mut h, b':');
    mix(&mut h, b':');
    for b in name.bytes() {
        mix(&mut h, b);
    }
    let h = h & HANDLER_ID_MAX;
    if h == 0 { 1 } else { h }
}

impl std::fmt::Debug for HandlerSpec {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("HandlerSpec")
            .field("storage_type", &self.storage_type)
            .field("has_state_type_id", &self.state_type_id.is_some())
            .field("has_remote_handler", &self.remote_handler.is_some())
            .field("has_param_bytes", &self.param_bytes.is_some())
            .finish()
    }
}

/// Type alias for stateful handler functions.
pub type StatefulHandler<S> = fn(&mut S);

/// Type alias for renderer functions.
pub type Renderer<S> = fn(&S) -> ElementBuilder;

/// A type-erased handler that can mutate state.
pub struct HandlerFn {
    /// The type-erased handler function
    inner: Box<dyn HandlerInner>,
    /// Which fields this handler modifies (for fine-grained reactivity)
    changes: ChangeSet,
    /// Storage type for this handler's state
    storage_type: StorageType,
    /// Table name for persisted state (None for non-persisted)
    table_name: Option<&'static str>,
}

trait HandlerInner: Send + Sync {
    fn state_type_id(&self) -> TypeId;
    fn create_state(&self) -> Box<dyn Any + Send + Sync>;
    fn call(&self, state: &mut dyn Any);
    fn call_with_context(&self, state: &mut dyn Any, ctx: &EventContext);
    fn needs_context(&self) -> bool;
    fn clone_box(&self) -> Box<dyn HandlerInner>;
    /// Get a unique identifier for this handler (function pointer address)
    fn fn_id(&self) -> usize;
}

/// Handler that takes only state (legacy, single-parameter).
struct TypedHandler<S: Default + Send + Sync + 'static> {
    handler: fn(&mut S),
    _marker: std::marker::PhantomData<S>,
}

/// Handler that takes state and EventContext (new, two-parameter).
struct TypedHandlerWithContext<S: Default + Send + Sync + 'static> {
    handler: fn(&mut S, &EventContext),
    _marker: std::marker::PhantomData<S>,
}

impl<S: Default + Send + Sync + 'static> HandlerInner for TypedHandler<S> {
    fn state_type_id(&self) -> TypeId {
        TypeId::of::<S>()
    }

    fn create_state(&self) -> Box<dyn Any + Send + Sync> {
        Box::new(S::default())
    }

    fn call(&self, state: &mut dyn Any) {
        if let Some(s) = state.downcast_mut::<S>() {
            (self.handler)(s);
        }
    }

    fn call_with_context(&self, state: &mut dyn Any, _ctx: &EventContext) {
        // Legacy handler ignores context
        self.call(state);
    }

    fn needs_context(&self) -> bool {
        false
    }

    fn clone_box(&self) -> Box<dyn HandlerInner> {
        Box::new(TypedHandler {
            handler: self.handler,
            _marker: std::marker::PhantomData,
        })
    }

    fn fn_id(&self) -> usize {
        self.handler as usize
    }
}

impl<S: Default + Send + Sync + 'static> HandlerInner for TypedHandlerWithContext<S> {
    fn state_type_id(&self) -> TypeId {
        TypeId::of::<S>()
    }

    fn create_state(&self) -> Box<dyn Any + Send + Sync> {
        Box::new(S::default())
    }

    fn call(&self, state: &mut dyn Any) {
        // If called without context, use empty context
        self.call_with_context(state, &EventContext::empty());
    }

    fn call_with_context(&self, state: &mut dyn Any, ctx: &EventContext) {
        if let Some(s) = state.downcast_mut::<S>() {
            (self.handler)(s, ctx);
        }
    }

    fn needs_context(&self) -> bool {
        true
    }

    fn clone_box(&self) -> Box<dyn HandlerInner> {
        Box::new(TypedHandlerWithContext {
            handler: self.handler,
            _marker: std::marker::PhantomData,
        })
    }

    fn fn_id(&self) -> usize {
        self.handler as usize
    }
}

impl Clone for HandlerFn {
    fn clone(&self) -> Self {
        Self {
            inner: self.inner.clone_box(),
            changes: self.changes,
            storage_type: self.storage_type,
            table_name: self.table_name,
        }
    }
}

impl HandlerFn {
    /// Create a new handler for the given MemoryState type (legacy API).
    /// Uses `ChangeSet::all()` for backwards compatibility.
    pub fn new<S: MemoryState>(handler: fn(&mut S)) -> Self {
        Self {
            inner: Box::new(TypedHandler {
                handler,
                _marker: std::marker::PhantomData,
            }),
            changes: ChangeSet::all(),
            storage_type: StorageType::Memory,
            table_name: None,
        }
    }

    /// Create a new handler for the given State type.
    /// Uses `ChangeSet::all()` for backwards compatibility.
    pub fn new_state<S: State + Default>(handler: fn(&mut S)) -> Self {
        Self::new_state_with_changes::<S>(handler, ChangeSet::all())
    }

    /// Create a new handler for the given State type with explicit ChangeSet.
    pub fn new_state_with_changes<S: State + Default>(
        handler: fn(&mut S),
        changes: ChangeSet,
    ) -> Self {
        let storage_type = S::STORAGE_TYPE;
        let table_name = if S::TABLE_NAME.is_empty() {
            None
        } else {
            Some(S::TABLE_NAME)
        };
        Self {
            inner: Box::new(TypedHandler {
                handler,
                _marker: std::marker::PhantomData,
            }),
            changes,
            storage_type,
            table_name,
        }
    }

    /// Create a new handler with context support for the given State type.
    /// Uses `ChangeSet::all()` for backwards compatibility.
    pub fn new_with_context<S: State + Default>(handler: fn(&mut S, &EventContext)) -> Self {
        Self::new_with_context_and_changes::<S>(handler, ChangeSet::all())
    }

    /// Create a new handler with context support for the given State type with explicit ChangeSet.
    pub fn new_with_context_and_changes<S: State + Default>(
        handler: fn(&mut S, &EventContext),
        changes: ChangeSet,
    ) -> Self {
        let storage_type = S::STORAGE_TYPE;
        let table_name = if S::TABLE_NAME.is_empty() {
            None
        } else {
            Some(S::TABLE_NAME)
        };
        Self {
            inner: Box::new(TypedHandlerWithContext {
                handler,
                _marker: std::marker::PhantomData,
            }),
            changes,
            storage_type,
            table_name,
        }
    }

    /// Get the ChangeSet for this handler.
    pub fn changes(&self) -> ChangeSet {
        self.changes
    }

    /// Get the TypeId of the state this handler operates on.
    pub fn state_type_id(&self) -> TypeId {
        self.inner.state_type_id()
    }

    /// Create a new default state of the correct type.
    pub fn create_state(&self) -> Box<dyn Any + Send + Sync> {
        self.inner.create_state()
    }

    /// Call the handler with the given state (legacy, no context).
    pub fn call(&self, state: &mut dyn Any) {
        self.inner.call(state);
    }

    /// Call the handler with the given state and event context.
    pub fn call_with_context(&self, state: &mut dyn Any, ctx: &EventContext) {
        self.inner.call_with_context(state, ctx);
    }

    /// Check if this handler needs context (uses 2-parameter signature).
    pub fn needs_context(&self) -> bool {
        self.inner.needs_context()
    }

    /// Get a unique identifier for this handler (function pointer address).
    ///
    /// This is used to match handlers during synced element updates,
    /// where we need to find the correct handler index for rebinding events.
    pub fn fn_id(&self) -> usize {
        self.inner.fn_id()
    }

    /// Get the storage type for this handler's state.
    pub fn storage_type(&self) -> StorageType {
        self.storage_type
    }

    /// Get the table name for persisted state (None for non-persisted).
    pub fn table_name(&self) -> Option<&'static str> {
        self.table_name
    }
}

impl std::fmt::Debug for HandlerFn {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("HandlerFn")
            .field("state_type_id", &self.state_type_id())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_handler_spec_debounce() {
        let spec = HandlerSpec::memory::<TestState>(test_handler);
        assert_eq!(spec.debounce_ms, 0);

        let spec = spec.debounce(300);
        assert_eq!(spec.debounce_ms, 300);
    }

    #[derive(Default)]
    struct TestState {
        count: i32,
    }

    impl MemoryState for TestState {}

    fn test_handler(state: &mut TestState) {
        state.count += 1;
    }
}
